# -*- coding: utf-8 -*-
"""multiple csv.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1J1qTkDwKItYKcF0mNHCdmEw5WCWfDbxO
"""

import os
import csv

# define the algorithm you want to run on each csv file
def your_algorithm(data):
    # your code here
    print(data[1])
    return data

# set the directory where your csv files are located
directory = "/content/"

# loop through all files in the directory
for filename in os.listdir(directory):
    if filename.endswith(".csv"):
        # read in the csv file
        with open(os.path.join(directory, filename)) as csvfile:
            data = list(csv.reader(csvfile))
        
        # run your algorithm on the data
        result = your_algorithm(data)
        
        # write the result to a txt file
        with open(os.path.join(directory, filename.split('.')[0] + '.txt'), 'w') as txtfile:
            txtfile.write(str(result))

